SET NOCOUNT ON;
SET XACT_ABORT ON;
SET ANSI_NULLS ON;
SET ANSI_PADDING ON;
SET ANSI_WARNINGS ON;
SET ARITHABORT ON;
SET CONCAT_NULL_YIELDS_NULL ON;
SET QUOTED_IDENTIFIER ON;
SET NUMERIC_ROUNDABORT OFF;
GO
IF OBJECT_ID(N'dbo.CHAT_SESSION', N'U') IS NULL
    THROW 50001, 'Run chat table scripts before script 14.', 1;
BEGIN TRANSACTION;
IF EXISTS (SELECT 1 FROM sys.key_constraints
           WHERE parent_object_id = OBJECT_ID(N'dbo.CHAT_SESSION')
             AND name = N'UQ_CHAT_SESSION_SessionKey')
    ALTER TABLE dbo.CHAT_SESSION DROP CONSTRAINT UQ_CHAT_SESSION_SessionKey;
IF EXISTS (SELECT 1 FROM sys.indexes
           WHERE object_id = OBJECT_ID(N'dbo.CHAT_SESSION')
             AND name = N'UQ_CHAT_SESSION_SessionKey')
    DROP INDEX UQ_CHAT_SESSION_SessionKey ON dbo.CHAT_SESSION;
IF EXISTS (SELECT 1 FROM sys.indexes
           WHERE object_id = OBJECT_ID(N'dbo.CHAT_SESSION')
             AND name = N'IX_CHAT_SESSION_SessionKey')
    DROP INDEX IX_CHAT_SESSION_SessionKey ON dbo.CHAT_SESSION;
CREATE INDEX IX_CHAT_SESSION_SessionKey
    ON dbo.CHAT_SESSION(SessionKey)
    WHERE SessionKey IS NOT NULL;
COMMIT TRANSACTION;
GO
